### PR TITLE
update bbb-api

### LINKED ISSUE #37: Can not create room
Hi,

with the newest Plugin version, I get this error:

BigBlueButton\Exceptions\BadResponseException thrown with message "Bad response, HTTP code: 501"

Stacktrace:
#10 BigBlueButton\Exceptions\BadResponseException in /var/www/html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:488
#9 BigBlueButton\BigBlueButton:processXmlResponse in /var/www/html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:264
#8 BigBlueButton\BigBlueButton:getMeetingInfo in /var/www/html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/classes/class.ilBigBlueButtonProtocol.php:147
#7 ilBigBlueButtonProtocol:isMeetingRecorded in /var/www/html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/classes/class.ilObjBigBlueButtonGUI.php:373
#6 ilObjBigBlueButtonGUI:showContent in /var/www/html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/classes/class.ilObjBigBlueButtonGUI.php:98
#5 ilObjBigBlueButtonGUI:performCommand in /var/www/html/ilias/Services/Repository/classes/class.ilObjectPluginGUI.php:165
#4 ilObjectPluginGUI:executeCommand in /var/www/html/ilias/Services/UICore/classes/class.ilCtrl.php:217
#3 ilCtrl:forwardCommand in /var/www/html/ilias/Services/Repository/classes/class.ilObjPluginDispatchGUI.php:45
#2 ilObjPluginDispatchGUI:executeCommand in /var/www/html/ilias/Services/UICore/classes/class.ilCtrl.php:217
#1 ilCtrl:forwardCommand in /var/www/html/ilias/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /var/www/html/ilias/ilias.php:23

-- GET Data --

ref_id                   : 350604
cmd                      : showContent
cmdClass                 : ilobjbigbluebuttongui
cmdNode                  : r6:me
baseClass                : ilobjplugindispatchgui
lang                     : de
limit                    : 9999

-- POST Data --

empty

-- Files --

empty

-- Cookies --

ilClientId               : iliasschoolmaster
PHPSESSID                : pl9e2oa7gluokgthrnu0bujsud
il_mb_slates             : {"engaged":true}
1044257661               : {"any_entry_engaged":true,"tools_engaged":false,"more_available":true,"entries":{"0:0":[0,0,0],"0:1":[0,1,0],"0:1:0":[0,1,0],"0:1:8":[0,0,0],"0:2":[0,0,0],"0:3":[0,0,0],"0:4":[0,0,0],"0:5":[0,0,0],"0:6":[0,0,0],"0:7":[0,0,0],"0:7:0":[0,0,0],"0:7:1":[0,1,0],"0:7:3":[0,1,0],"0:7:4":[0,0,0],"0:7:5":[0,0,0],"0:7:6":[0,0,0],"0:7:8":[0,0,0],"0:7:9":[0,1,0],"0:7:10":[0,0,0],"0:8":[0,0,0],"0:9":[0,0,0]},"tools":{},"known_tools":[],"last_active_top":"0:1"}

-- Session --

tbl_limit                : 9999
referer_ref_id           : 350604
_authsession_expired     : 0
SessionType              : 2
_authsession_authenticated: 1
_authsession_user_id     : 431
orig_request_target      : 
has_to_accept_agr_in_session: 1
lang                     : de
ILIAS\Init\StartupSequence\StartUpSequenceDispatcher_passed: 1
il_pd_history            : 
pditems_0_blnav          : ::0
pdmem_0_blnav            : ::0
pdtasks_0_blnav          : ::0
pdnews_0_blnav           : ::0
pdmail_0_blnav           : ::0
awrn_last_update         : 1669647158
awrn_nr_users            : 119
awrn_nr_husers           : 0
il_rep_mode              : flat
il_rep_ref_id            : 79685
il_nav_history           : a:4:{s:7:"350604:";a:7:{s:2:"id";s:7:"350604:";s:6:"ref_id";s:6:"350604";s:4:"link";s:80:"https://kivinet.de/ilias/goto.php?target=xbbb_350604&client_id=iliasschoolmaster";s:5:"title";s:1:"3";s:4:"type";s:4:"xbbb";s:10:"sub_obj_id";s:0:"";s:9:"goto_link";s:0:"";}s:6:"79685:";a:7:{s:2:"id";s:6:"79685:";s:6:"ref_id";s:5:"79685";s:4:"link";s:78:"https://kivinet.de/ilias/goto.php?target=grp_79685&client_id=iliasschoolmaster";s:5:"title";s:14:"Muster - Kopie";s:4:"type";s:3:"grp";s:10:"sub_obj_id";s:0:"";s:9:"goto_link";s:0:"";}s:7:"348541:";a:7:{s:2:"id";s:7:"348541:";s:6:"ref_id";s:6:"348541";s:4:"link";s:80:"https://kivinet.de/ilias/goto.php?target=xbbb_348541&client_id=iliasschoolmaster";s:5:"title";s:1:"6";s:4:"type";s:4:"xbbb";s:10:"sub_obj_id";s:0:"";s:9:"goto_link";s:0:"";}s:7:"350600:";a:7:{s:2:"id";s:7:"350600:";s:6:"ref_id";s:6:"350600";s:4:"link";s:80:"https://kivinet.de/ilias/goto.php?target=xbbb_350600&client_id=iliasschoolmaster";s:5:"title";s:1:"2";s:4:"type";s:4:"xbbb";s:10:"sub_obj_id";s:0:"";s:9:"goto_link";s:0:"";}}
news_99891_blnav         : ::0
table                    : Array
                         (
                             [cmpspl] => Array
                                 (
                                     [431] => Array
                                         (
                                             [offset] => 0
                                         )
                         
                                 )
                         
                         )
                         
referer                  : /ilias/ilias.php?ref_id=350604&cmd=editProperties&cmdClass=ilobjbigbluebuttongui&cmdNode=r6:me&baseClass=ilobjplugindispatchgui

-- Server/Request Data --

SCRIPT_URL               : /ilias/ilias.php
SCRIPT_URI               : https://kivinet.de/ilias/ilias.php
HTTPS                    : on
SSL_TLS_SNI              : kivinet.de
HTTP_HOST                : kivinet.de
HTTP_CONNECTION          : keep-alive
HTTP_SEC_CH_UA           : "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"
HTTP_SEC_CH_UA_MOBILE    : ?0
HTTP_SEC_CH_UA_PLATFORM  : "Windows"
HTTP_UPGRADE_INSECURE_REQUESTS: 1
HTTP_DNT                 : 1
HTTP_USER_AGENT          : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
HTTP_ACCEPT              : text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
HTTP_SEC_FETCH_SITE      : same-origin
HTTP_SEC_FETCH_MODE      : navigate
HTTP_SEC_FETCH_USER      : ?1
HTTP_SEC_FETCH_DEST      : document
HTTP_REFERER             : https://kivinet.de/ilias/ilias.php?ref_id=350604&cmd=editProperties&cmdClass=ilobjbigbluebuttongui&cmdNode=r6:me&baseClass=ilobjplugindispatchgui
HTTP_ACCEPT_ENCODING     : gzip, deflate, br
HTTP_ACCEPT_LANGUAGE     : de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
HTTP_COOKIE              : ilClientId=iliasschoolmaster; PHPSESSID=pl9e2 (SHORTENED FOR SECURITY); ilClientId=iliasschoolmaster; il_mb_slates={"engaged":true}; 1044257661={"any_entry_engaged":true,"tools_engaged":false,"more_available":true,"entries":{"0:0":[0,0,0],"0:1":[0,1,0],"0:1:0":[0,1,0],"0:1:8":[0,0,0],"0:2":[0,0,0],"0:3":[0,0,0],"0:4":[0,0,0],"0:5":[0,0,0],"0:6":[0,0,0],"0:7":[0,0,0],"0:7:0":[0,0,0],"0:7:1":[0,1,0],"0:7:3":[0,1,0],"0:7:4":[0,0,0],"0:7:5":[0,0,0],"0:7:6":[0,0,0],"0:7:8":[0,0,0],"0:7:9":[0,1,0],"0:7:10":[0,0,0],"0:8":[0,0,0],"0:9":[0,0,0]},"tools":{},"known_tools":[],"last_active_top":"0:1"}
HTTP_SEC_GPC             : 1
PATH                     : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
SERVER_SIGNATURE         : <address>Apache/2.4.29 (Ubuntu) Server at kivinet.de Port 443</address>
                         
SERVER_SOFTWARE          : Apache/2.4.29 (Ubuntu)
SERVER_NAME              : kivinet.de
SERVER_ADDR              : 62.138.184.135
SERVER_PORT              : 443
REMOTE_ADDR              : 185.123.7.54
DOCUMENT_ROOT            : /var/www/html
REQUEST_SCHEME           : https
CONTEXT_PREFIX           : 
CONTEXT_DOCUMENT_ROOT    : /var/www/html
SERVER_ADMIN             : wolfgang.huebsch@kivinan.de
SCRIPT_FILENAME          : /var/www/html/ilias/ilias.php
REMOTE_PORT              : 56494
GATEWAY_INTERFACE        : CGI/1.1
SERVER_PROTOCOL          : HTTP/1.1
REQUEST_METHOD           : GET
QUERY_STRING             : ref_id=350604&cmd=showContent&cmdClass=ilobjbigbluebuttongui&cmdNode=r6:me&baseClass=ilobjplugindispatchgui
REQUEST_URI              : /ilias/ilias.php?ref_id=350604&cmd=showContent&cmdClass=ilobjbigbluebuttongui&cmdNode=r6:me&baseClass=ilobjplugindispatchgui
SCRIPT_NAME              : /ilias/ilias.php
PHP_SELF                 : /ilias/ilias.php
REQUEST_TIME_FLOAT       : 1669647160.8174
REQUEST_TIME             : 1669647160

-- Environment Variables --

empty

### LINKED ISSUE #45: Breakout-Room
ILIAS: 7.20
BBB: 2.0.2

Breakout rooms can no longer be created.
grafik

### LINKED ISSUE #54: Link/Menu Item "Learn Analytics Dashboard" is missing
When clicking the "Manage User" gear the Link to the  Learn Analytics Dashboard is missing. It appears when using Greenlight and other plugins (e.g. Moodle BBB-Plugin). 

Screenshot from Greenlight:
Bildschirmfoto_2023-10-31_09-25-12

### PR DESCRIPTION
**Pull request by xJuvi**
This PR brings the bbb-api to the current dev-master and fixes #45 fixes #37 and fixes #54 as well.

With the current dev-master unsetted parameters won't be sent as "false" - now these are NULL.

### CODE REVIEW

**Comment by xJuvi** [comment]
Oh yes I found the error. 
With the new API is an hashing algorithm required. 

I think we can remove the UrlBuilder because it was called in the parent class. Our implementation is unused I think.

**Comment by thwien** [comment]
I tried using PR #53 into local master copy to solve #45 but I got the following error messages:

**ERROR: Whoops\Handler\CallbackHandler::handle:398 0 ilObjBigBlueButton::setMaxConcurrentSessionsMsg(): Argument #1 ($message) must be of type string, null given, called in /var/www/project/public_html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/classes/class.ilObjBigBlueButton.php on line 204 in /var/www/project/public_html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/classes/class.ilObjBigBlueButton.php:686#0 /var/www/project/public_html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/classes/class.ilObjBigBlueButton.php(204): ilObjBigBlueButton->setMaxConcurrentSessionsMsg()**

This was caused by a NULL value in database table rep_robj_xbbb_conf.sess_msg_concurrent. Only if I checked the experimental session management in BBB plugin this error message is gone. So, the default value of rep_robj_xbbb_conf.sess_msg_concurrent IMHO should be a valid number or the BBB plugin script has to check the values from database before processing it.

**ERROR: Whoops\Handler\CallbackHandler::handle:398 0 Class "ilBBB" not found in /var/www/project/public_html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/classes/class.ilBigBlueButtonProtocol.php:32#0 /var/www/project/public_html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/classes/class.ilObjBigBlueButtonGUI.php(307): ilBigBlueButtonProtocol->__construct()**

I have no clue why this class was not found by BBB plugin. The class file exists with this class name. Maybe it is better to wait until you merge this PR to a released version. Without this PR it seems that we cannot upgrade from Ilias 7 to 8.

**Comment by xJuvi** [comment]
Hi @thwien 
that are two different bugs. 

I currently doesn't have access to a running ilias instance so i can't confirm the types in the database. But i think, the field isn't _NULL_, but there is no value (empty). The type casting checks only for null values. This PR is for updating the BBB API, so i will create this evening a new PR to fix this.

The second bug is caused removing to require the class files and start using composer classmapp. The composer file is correct implemented, but was not running before implementing in this repo. So composer doesn't have created a classmap for ilias plugin files. I will upload this evening a new dev version from the BBB API (minor phph8 issues) and fix then the composer lock file.

Kind regards

**Review by waddahadel — CHANGES_REQUESTED** [review]
The parameter of the hashingalgorithm is not included in the __construct method in the ilBBB class,  `   public function __construct($securitySecret=null, $baseUrl=null,$hashingAlgorithm)
    {
        parent::__construct();
        $this->securitySecret = $securitySecret;
        $this->bbbServerBaseUrl = $baseUrl;
        $this->urlBuilder       = new UrlBuilder($this->securitySecret, $this->bbbServerBaseUrl,$hashingAlgorithm);
      `

and the same issue occurs in the __construct method the ilBigBlueButtonProtocol class, the fix is to include the hashing algorithm  file: `use BigBlueButton\Enum\HashingAlgorithm;`

and to change the __construct function to : ` public function __construct($object)
    {
        $this->object = $object;
        $this->bbb = new ilBBB($this->object->getSvrSalt(), $this->object->getSvrPublicURL(), HashingAlgorithm::SHA_256);
        $this->meetings = $this->bbb->getMeetings();
    }`  

Everything else works just fine after those fixes, creating a room and also breakout rooms are available again, if those changes are made a merge is then possible..

**Comment by xJuvi** [comment]
Hi @waddahadel 
thanks for your request.
Let me ask you another solution:

What do you think about the removal of the UrlBuilder and the usage from the original API class? We can set the server url and secret to the parent constructor and the original API class can make the other magics around?

I checked this pllugin code fast and i think it should be possible without major changes.

Kind regdards

**Comment by waddahadel** [comment]
hello @xJuvi ,

I think that might be possible as well, I will fork the repo from your side and make a pr there when I'm done, I also wanted to ask if you can make another pr with your changes to branch release_7, I think most of the changes will work there as well with some slight changes right? cause we have the same issue with breakout rooms on version 2.0.2 - you may just do the temporary fix about the parameters and I will change that later after we merge-  , that would be perfect, thanks for the help

**Comment by waddahadel** [comment]
Hello @xJuvi ,
I'm a bit of a newbie to ILIAS plugins development so I couldn't make the changes you mentioned, I made an attempt but messed a lot of stuff up, maybe I don't understand the logic well enough

**Comment by xJuvi** [comment]
Hi @waddahadel 
i made a new branch to test my idea. In this commit you can find them:
https://github.com/xJuvi/BigBlueButton-Ilias-Plugin/commit/a41c967c7b026c9d64761e131fe69972c8fe34b5

If it's working, we can add the change into this PR.

Kind regards.

**Comment by waddahadel** [comment]
Hello @xJuvi ,

I will test it right away, then I will inform you, Also wanted to ask if the api updates for this branch might also work for release_7, I think the changes are made in the vendor directory only right? I might replace the codes and play around with it if that is the case, meanwhile I will check you new changes

**Comment by xJuvi** [comment]
Hi @waddahadel 
yeah, to update the files, fork the repo and run a composer update. I can made a second PR if your tests are successful, then we can maintain the release_7 branch also.

Thanks for your help.

**Review by xJuvi — COMMENTED** [review]
---- fail

**Comment by waddahadel** [comment]
Hey, just tested the test_api_update branch, everything works smoothly on ILIAS 8, breakout rooms are also back as well, got the changes you made and the workaround around that spaghetti code I made at first, neat, you can make  a pr with that branch, we are ready to merge,  I'll try to fix the branch for release_7

**Comment by xJuvi** [comment]
hi @waddahadel 
i made a new commit to add the new changes into this PR. Now @jeph864 can merge.
Thanks for your testen. To fix the "release_7" branch we only must update the api options and change the construtor. I created a new branch on my fork https://github.com/xJuvi/BigBlueButton-Ilias-Plugin/tree/update_api_release_7 to realize this.

Thanks!

**Review by waddahadel — APPROVED** [review]

**Pull request merged**
